name: docker
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker run hello-world
    - run: bash container.sh && bash container.sh
    - run: docker build -t minside .
    - run: docker run -d --name site -p 8080:8000 minside
    - run: sleep 2 && curl -f localhost:8080
    - run: docker rm -f site
    - run: docker run -d --name site2 -p 9090:8000 minside
    - run: sleep 2 && curl -f localhost:9090
    - run: docker rm -f site2
    - run: bash image.sh
    - run: bash image.sh
    - run: bash volume.sh
